# Numpy

In [1]:
import numpy as np

In [2]:
arry1 = np.array([5.5,9,10], dtype=float) 

In [3]:
arry1

array([ 5.5,  9. , 10. ])

In [4]:
arry2 = np.array([1,2,3],[4,5,6],[7,8,9])
arry2

ValueError: only 2 non-keyword arguments accepted

In [5]:
arry2 = np.array([(3.5,8,11), (4,7,9), (2,2,1.1)], dtype=float)
arry2


array([[ 3.5,  8. , 11. ],
       [ 4. ,  7. ,  9. ],
       [ 2. ,  2. ,  1.1]])

In [6]:
arry4 = np.array([6.4,10,15])
arry5 = np.array([(3.5,8,11), (4,7,9), (2,3,1.1)], dtype=float)
arry6 = arry5 - arry4
print("Fark arry5 - arry4: ",arry6)

Fark arry5 - arry4:  [[ -2.9  -2.   -4. ]
 [ -2.4  -3.   -6. ]
 [ -4.4  -7.  -13.9]]


In [7]:
arry6 = np.subtract(arry4,arry5)
print("Fark arry4 - arry5: ",arry6)

Fark arry4 - arry5:  [[ 2.9  2.   4. ]
 [ 2.4  3.   6. ]
 [ 4.4  7.  13.9]]


In [8]:
arry6 = arry5 + arry4
print("Fark arry5 + arry4: ",arry6)


Fark arry5 + arry4:  [[ 9.9 18.  26. ]
 [10.4 17.  24. ]
 [ 8.4 13.  16.1]]


In [9]:
arry7 = np.array([(10,13,9),(1,8,15)], dtype=float)
arry8 = arry7 > 5
print(arry8)

[[ True  True  True]
 [False  True  True]]


In [10]:
print(arry7[arry8])

[10. 13.  9.  8. 15.]


In [11]:
arry9  = np.array([5,8,3])
arry10 = np.array([2,7,6])
arry11 = np.dot(arry9, arry10)
print("Çarpım: ",arry11) #5*2 + 8*7 + 3* 6

Çarpım:  84


In [12]:
arry12 = np.array([(2,7,6),(12,23,212),(23,232,12)])
result = np.delete(arry12,0,-1)
result

array([[  7,   6],
       [ 23, 212],
       [232,  12]])

In [13]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
np.arange(5,20,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
zeros = np.zeros((3,4))
zeros[1,2] = 10
print(zeros)

[[ 0.  0.  0.  0.]
 [ 0.  0. 10.  0.]
 [ 0.  0.  0.  0.]]


In [17]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.empty((2,3)) 


array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.random.randint(0,100)

51

In [20]:
np.random.randint(0,100,10)

array([65, 75,  0, 73, 24, 84, 43, 66, 86, 37])

In [21]:
np.random.rand(3)

array([0.68120204, 0.6996338 , 0.14059942])

In [22]:
ref_arry = np.array([1,2,3,4,5,6,7,8,9])
print("ref_arry toplamı  : ",ref_arry.sum())
print("ref_arry en büyük : ",np.max(ref_arry))
print("ref_arry en küçük : ",np.min(ref_arry))
print("ref_arry karekök  : ",np.sqrt(ref_arry))
print("ref_arry ortalama : ",ref_arry.mean())
print("ref_arry logaritma: ",np.log(ref_arry))
print("ref_arry transpoz : ",np.transpose(ref_arry))
print("ref_arry sinüs    : ",np.sin(ref_arry))
print("ref_arry e üssü alma: ",np.exp(ref_arry))
print("ref_arry karesi   : ",np.square(ref_arry))

ref_arry toplamı  :  45
ref_arry en büyük :  9
ref_arry en küçük :  1
ref_arry karekök  :  [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
ref_arry ortalama :  5.0
ref_arry logaritma:  [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
ref_arry transpoz :  [1 2 3 4 5 6 7 8 9]
ref_arry sinüs    :  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
ref_arry e üssü alma:  [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
ref_arry karesi   :  [ 1  4  9 16 25 36 49 64 81]


# Pandas

In [23]:
import pandas as pd

In [24]:
data = ["a","b","c","d","e","f","g","h","i"]
pd.Series(data)

0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
8    i
dtype: object

In [25]:
index = [5,6,7,8,9,10,11,12,13]
data = ["a","b","c","d","e","f","g","h","i"]
pd.Series(data, index)

5     a
6     b
7     c
8     d
9     e
10    f
11    g
12    h
13    i
dtype: object

In [26]:
numpyArray = ["Sefiller", "Suç ve Ceza", "Beyaz Gemi", "İki Şehrin Hikáyesi", "Osmancık"]
numpyIndex = ["Victor Hugo", "Tolstoy", "Cengiz Aytmatov", "Charles Dickens", "Tarık Buğra"]
author = np.array(numpyIndex)
books = np.array(numpyArray)
pd.Series(data=books, index=author)

Victor Hugo                   Sefiller
Tolstoy                    Suç ve Ceza
Cengiz Aytmatov             Beyaz Gemi
Charles Dickens    İki Şehrin Hikáyesi
Tarık Buğra                   Osmancık
dtype: object

In [27]:
myIndex = np.array(["v1","v2","v3","v4","v5"])
numbers = np.array([1,2,3,4,5])
pd.Series(data=numbers, index=myIndex, dtype=float)

v1    1.0
v2    2.0
v3    3.0
v4    4.0
v5    5.0
dtype: float64

In [28]:
dictionary = {"a":"₺(Türk Lirası)","b":"$(Amerikan Doları)","c":"€(Avrupa para birimi)"}
pd.Series(data=dictionary)

a           ₺(Türk Lirası)
b       $(Amerikan Doları)
c    €(Avrupa para birimi)
dtype: object

In [29]:
dictionary = {'a': 0, 'b':1, 'c':2, 'd':3, 'e':4, 'f':5}
pdSeries = pd.Series(data=dictionary)
pdSeries

a    0
b    1
c    2
d    3
e    4
f    5
dtype: int64

In [30]:
print("pdSeries nesnesinin boyutu : ",pdSeries.ndim)
print("pdSeries nesnesinin tipi   : ",pdSeries.dtype)
print("pdSeries nesnesinin satır ve sütun sayısı: ",pdSeries.shape)
print("pdSeries nesnesinin değerler toplamı : ",pdSeries.sum())
print("pdSeries nesnesinin en küçük değeri : ",pdSeries.min())
print("pdSeries nesnesinin en büyük değeri : ",pdSeries.max())
print("pdSeries nesnesinin medyanı : ",pdSeries.median())

pdSeries nesnesinin boyutu :  1
pdSeries nesnesinin tipi   :  int64
pdSeries nesnesinin satır ve sütun sayısı:  (6,)
pdSeries nesnesinin değerler toplamı :  15
pdSeries nesnesinin en küçük değeri :  0
pdSeries nesnesinin en büyük değeri :  5
pdSeries nesnesinin medyanı :  2.5


In [31]:
dictionary = {'a': 6, 'b':7, 'c':8, 'd':9}
pdSeries = pd.Series(data=dictionary)
pdSeries

a    6
b    7
c    8
d    9
dtype: int64

In [32]:
print("pdSeries nesnesinin kendisiyle toplamı: ",pdSeries + pdSeries)
print("pdSeries nesnesinin karekök değerleri : ",np.sqrt(pdSeries))
print("pdSeries nesnesinin kendisiyle çarpımı: ",pdSeries * pdSeries)
print("pdSeries nesnesinin kendisiyle bölümü : ",pdSeries / pdSeries)

pdSeries nesnesinin kendisiyle toplamı:  a    12
b    14
c    16
d    18
dtype: int64
pdSeries nesnesinin karekök değerleri :  a    2.449490
b    2.645751
c    2.828427
d    3.000000
dtype: float64
pdSeries nesnesinin kendisiyle çarpımı:  a    36
b    49
c    64
d    81
dtype: int64
pdSeries nesnesinin kendisiyle bölümü :  a    1.0
b    1.0
c    1.0
d    1.0
dtype: float64


In [33]:
print(pdSeries[pdSeries > (pdSeries.sum() / pdSeries.median())])


a    6
b    7
c    8
d    9
dtype: int64


In [34]:
print(pdSeries[pdSeries <= 7])

a    6
b    7
dtype: int64


### dataframe

In [35]:
departments = ["IT department", "Human Resources", "AR-GE department"]
dataFrom = pd.DataFrame(departments)
dataFrom

0
0     IT department
1   Human Resources
2  AR-GE department

In [36]:
dictionary = {
                "Isim": ["Murat", "Atıl", "Betül", "Adem", "Merve"],
                "Yas" : [28, 30, 25, 22, 19],
                "Maas": [3200, 5000, 3500, 3999, 2800]
             }

In [37]:
dataFrom = pd.DataFrame(dictionary) 
dataFrom

Isim  Yas  Maas
0  Murat   28  3200
1   Atıl   30  5000
2  Betül   25  3500
3   Adem   22  3999
4  Merve   19  2800

In [38]:
head = dataFrom.head(2)  
head

Isim  Yas  Maas
0  Murat   28  3200
1   Atıl   30  5000

In [44]:
tail = dataFrom.tail(3)
tail

Isim  Yas  Maas
2  Betül   25  3500
3   Adem   22  3999
4  Merve   19  2800

In [45]:
dictionary = {
    'İsim': pd.Series(['Mustafa','Ahmet','İbrahim','Betül'],
                      index=['a1','a2','a3','a4']),
    'Meslek': pd.Series(['İmam','Mühendis','Pentester'],
                       index=['a1','a2','a3']),
    'Maaş':pd.Series([5000 , 7000, None, 4000],
                     index=['a1','a2','a3',"a4"])
}
dataFrm = pd.DataFrame(dictionary)
dataFrm

İsim     Meslek    Maaş
a1  Mustafa       İmam  5000.0
a2    Ahmet   Mühendis  7000.0
a3  İbrahim  Pentester     NaN
a4    Betül        NaN  4000.0

In [46]:
dataFrm['Maaş']

a1    5000.0
a2    7000.0
a3       NaN
a4    4000.0
Name: Maaş, dtype: float64

In [47]:
dataFrm['Maaş'][0]

5000.0

In [48]:
dataFrm.loc['a2']

İsim         Ahmet
Meslek    Mühendis
Maaş          7000
Name: a2, dtype: object

In [49]:
dataFrm.loc[:,["Meslek","Maaş"]]

Meslek    Maaş
a1       İmam  5000.0
a2   Mühendis  7000.0
a3  Pentester     NaN
a4        NaN  4000.0

In [50]:
dataFrm.loc[["a1","a3"],["İsim","Maaş"]]

İsim    Maaş
a1  Mustafa  5000.0
a3  İbrahim     NaN

### Sütun ve Satır Ekleme - Silme

In [51]:
data = {
    'İsim': pd.Series(['Ayşe','Mahmut','Hatice'],
                      index=['*','**','***']),
    'Meslek': pd.Series(['Doktor','Polis','Öğretmen'],
                       index=['*','**','***'])
}
dataFrame = pd.DataFrame(data)
dataFrame

İsim    Meslek
*      Ayşe    Doktor
**   Mahmut     Polis
***  Hatice  Öğretmen

In [52]:
dataFrame['Maaş'] = pd.Series([7500,5000,5000],index=['*','**','***'])
dataFrame

İsim    Meslek  Maaş
*      Ayşe    Doktor  7500
**   Mahmut     Polis  5000
***  Hatice  Öğretmen  5000

In [53]:
dataFrame.pop('Meslek')
dataFrame

İsim  Maaş
*      Ayşe  7500
**   Mahmut  5000
***  Hatice  5000

In [54]:
dataFrame['Meslek'] = pd.Series(['Doktor','Polis','Öğretmen'],index=['*','**','***'])
dataFrame

İsim  Maaş    Meslek
*      Ayşe  7500    Doktor
**   Mahmut  5000     Polis
***  Hatice  5000  Öğretmen

In [55]:
newDict = {
    'İsim':pd.Series(['Hakan'],index=['****']),
    'Meslek':pd.Series(['Pilot'],index=['****']),
    'Maaş':pd.Series([10000],index=['****'])
}
dataFrame2=pd.DataFrame(newDict)
result = dataFrame.append(dataFrame2)
result

İsim   Maaş    Meslek
*       Ayşe   7500    Doktor
**    Mahmut   5000     Polis
***   Hatice   5000  Öğretmen
****   Hakan  10000     Pilot

In [56]:
result = result.drop('****')
result


İsim  Maaş    Meslek
*      Ayşe  7500    Doktor
**   Mahmut  5000     Polis
***  Hatice  5000  Öğretmen

### IMDB Film veri analizi

In [57]:
dataFrame = pd.read_csv("IMDB-Movie-Data.csv")
# "IMDB-Movie-Data.csv" yi dahil etmek


In [58]:
dataFrame.head(3)

Rank                    Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1     2               Prometheus  Adventure,Mystery,Sci-Fi   
2     3                    Split           Horror,Thriller   

                                         Description            Director  \
0  A group of intergalactic criminals are forced ...          James Gunn   
1  Following clues to the origin of mankind, a te...        Ridley Scott   
2  Three girls are kidnapped by a man with a diag...  M. Night Shyamalan   

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121   
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124   
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117   

   Rating   Votes  Revenue (Millions)  Metascore  
0     8.1  757074              333.13       76.0  
1     7.0  485820              126.46       65.0  
2     7.3  157606              138.12       62.0

In [59]:
dataFrame.tail(2)

Rank         Title                  Genre  \
998   999  Search Party       Adventure,Comedy   
999  1000    Nine Lives  Comedy,Family,Fantasy   

                                           Description          Director  \
998  A pair of friends embark on a mission to reuni...    Scot Armstrong   
999  A stuffy businessman finds himself trapped ins...  Barry Sonnenfeld   

                                                Actors  Year  \
998  Adam Pally, T.J. Miller, Thomas Middleditch,Sh...  2014   
999  Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...  2016   

     Runtime (Minutes)  Rating  Votes  Revenue (Millions)  Metascore  
998                 93     5.6   4881                 NaN       22.0  
999                 87     5.3  12435               19.64       11.0

In [60]:
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Rank                1000 non-null   int64  
 1   Title               1000 non-null   object 
 2   Genre               1000 non-null   object 
 3   Description         1000 non-null   object 
 4   Director            1000 non-null   object 
 5   Actors              1000 non-null   object 
 6   Year                1000 non-null   int64  
 7   Runtime (Minutes)   1000 non-null   int64  
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64  
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB


In [61]:
dataFrame.describe()

Rank         Year  Runtime (Minutes)       Rating         Votes  \
count  1000.000000  1000.000000        1000.000000  1000.000000  1.000000e+03   
mean    500.500000  2012.783000         113.172000     6.723200  1.698083e+05   
std     288.819436     3.205962          18.810908     0.945429  1.887626e+05   
min       1.000000  2006.000000          66.000000     1.900000  6.100000e+01   
25%     250.750000  2010.000000         100.000000     6.200000  3.630900e+04   
50%     500.500000  2014.000000         111.000000     6.800000  1.107990e+05   
75%     750.250000  2016.000000         123.000000     7.400000  2.399098e+05   
max    1000.000000  2016.000000         191.000000     9.000000  1.791916e+06   

       Revenue (Millions)   Metascore  
count          872.000000  936.000000  
mean            82.956376   58.985043  
std            103.253540   17.194757  
min              0.000000   11.000000  
25%             13.270000   47.000000  
50%             47.985000   59.500000  
75%            113.715000   72.000000  
max            936.630000  100.000000

In [62]:
dataFrame['Year'].describe()

count    1000.000000
mean     2012.783000
std         3.205962
min      2006.000000
25%      2010.000000
50%      2014.000000
75%      2016.000000
max      2016.000000
Name: Year, dtype: float64

In [63]:
dataFrame.shape

(1000, 12)

In [64]:
dataFrame['Revenue (Millions)'].max()

936.63

In [65]:
dataFrame[dataFrame["Title"] == "John Wick"]['Rank'].iloc[0]

54

In [66]:
dataFrame[dataFrame['Year'] == 2014]['Title']

0           Guardians of the Galaxy
36                     Interstellar
53                        John Wick
65     Kingsman: The Secret Service
83                        Gone Girl
                   ...             
981                           Annie
983                   Let's Be Cops
987                    Endless Love
989                           Selma
998                    Search Party
Name: Title, Length: 98, dtype: object

In [67]:
dataFrame['Actors'].head(5)

0    Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...
1    Noomi Rapace, Logan Marshall-Green, Michael Fa...
2    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...
3    Matthew McConaughey,Reese Witherspoon, Seth Ma...
4    Will Smith, Jared Leto, Margot Robbie, Viola D...
Name: Actors, dtype: object